name: deploy-image-and-pr

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          cache: false
      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}
      - run: go test ./...

  build-and-push-image:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
      - name: 'Google Cloud Auth'
        uses: google-github-actions/auth@v2
        with: 
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - name: 'Setup Docker Buildx'
        uses: docker/setup-buildx-action@v3
      - name: 'Configure Docker'
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev
      - name: 'Build and Push image to Artifact Registry'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: Dockerfile
          tags: asia-northeast1-docker.pkg.dev/ouchihub/ouchi-hub/backend:${{ github.sha }}

  pull-request:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-image
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          repository: akimoto-junya/ouchi-hub-manifests
      - name: 'Update tag'
        run: sed -i -E 's/(asia-northeast1-docker.pkg.dev\/ouchihub\/ouchi-hub\/backend:)[0-9a-z]+/\1${{ github.sha }}/' backend/deployment.yaml
      - name: 'Create Pull Request'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          commit-message: 'Update backend image tag'
          delete-branch: true
          title: 'Update backend image tag'
          branch: update-backend-image-tag
